### PR TITLE
Use ModifyConstant for worldborder command patch

### PR DESCRIPTION
**Pull request by PercyDan54**
Supersedes #19

### CODE REVIEW

**Comment by Mysticpasta1** [comment]
I didn't see this until now

**Comment by PercyDan54** [comment]
> I didn't see this until now

This change should make 1.19 and 1.20 both work, is it ok?

**Comment by Mysticpasta1** [comment]
it should be fine but I would go ahead and check it in production on a 1.20.1 fabric version and a 1.19.2 fabric version

**Comment by PercyDan54** [comment]
> it should be fine but I would go ahead and check it in production on a 1.20.1 fabric version and a 1.19.2 fabric version

1.19.2 will definitely NOT work because of
https://github.com/PercyDan54/BorderRemover/issues/11#issuecomment-1465182593

However 1.19.4 and 1.20.1 seems working, please check again for me and tell me the result

**Pull request merged**
