### PR TITLE
1.20.1 fabric

### PR DESCRIPTION
**Pull request by Mysticpasta1**
Update to 1.20.1 fabric, I would also like this on Curseforge pls

### CODE REVIEW

**Comment by PercyDan54** [comment]
Afaik this already works on 1.20.1 so I didn't update the game dependency to avoid break old versions if possible, is there anything I missed?

**Comment by Mysticpasta1** [comment]
if (time > 0L) {
                worldBorder.interpolateSize(d, distance, time);
                if (distance > d) {
                    source.sendFeedback(Text.translatable("commands.worldborder.set.grow", String.format(Locale.ROOT, "%.1f", distance), Long.toString(time / 1000L)), true);
                    source.sendFeedback(() -> Text.translatable("commands.worldborder.set.grow", String.format(Locale.ROOT, "%.1f", distance), Long.toString(time / 1000L)), true);
                } else {
                    source.sendFeedback(Text.translatable("commands.worldborder.set.shrink", String.format(Locale.ROOT, "%.1f", distance), Long.toString(time / 1000L)), true);
                    source.sendFeedback(() -> Text.translatable("commands.worldborder.set.shrink", String.format(Locale.ROOT, "%.1f", distance), Long.toString(time / 1000L)), true);
                }
            } else {
                worldBorder.setSize(distance);
                source.sendFeedback(Text.translatable("commands.worldborder.set.immediate", String.format(Locale.ROOT, "%.1f", distance)), true);
                source.sendFeedback(() -> Text.translatable("commands.worldborder.set.immediate", String.format(Locale.ROOT, "%.1f", distance)), true);
            }
            return (int) (distance - d);
        }

**Comment by Mysticpasta1** [comment]
the Text.translatable's are now Suppilers

**Comment by Mysticpasta1** [comment]
so it breaks on 1.20.1 fabric

there are also updates for cloth config and mod menu

**Comment by Mysticpasta1** [comment]
can you also add it to Curseforge pls :D

**Comment by PercyDan54** [comment]
> can you also add it to Curseforge pls :D

Curseforge sucked so I may consider uploading to Modrinth, but I was too lazy to write the description thing for it

**Comment by PercyDan54** [comment]
> so it breaks on 1.20.1 fabric
> 
> there are also updates for cloth config and mod menu

What about #20

**Pull request closed without merging**
